// Catalogue houses shown in the storefront's browse-by-brand directory.
export const BRAND_HOUSES = [
  "Dior",
  "Chanel",
  "Yves Saint Laurent",
  "Giorgio Armani",
  "Tom Ford",
  "Creed",
  "Maison Francis Kurkdjian",
  "Le Labo",
  "Byredo",
  "Jo Malone London",
  "Maison Margiela",
  "Prada",
  "Gucci",
  "Versace",
  "Dolce & Gabbana",
  "Valentino",
  "Jean Paul Gaultier",
  "Paco Rabanne",
  "Hermès",
  "Lancôme",
  "Burberry",
  "Calvin Klein",
  "Hugo Boss",
  "Carolina Herrera",
  "Viktor & Rolf",
  "Givenchy",
  "Bvlgari",
  "Montblanc",
  "Azzaro",
  "Narciso Rodriguez",
  "Parfums de Marly",
  "Diptyque",
  "Penhaligon's",
  "Initio Parfums Privés",
  "Mugler",
];
